// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvnotrffnorlbibaccvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52bm90cmZmbm9ybGJpYmFjY3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzQ0MDQsImV4cCI6MjA3MDc1MDQwNH0.fopcOh95nRtNwIo7nrkEXPx_dr_u8lhLaMCRs4bG53g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});